#server:
 # type: simple
  #applicationContextPath: /application
 # adminContextPath: /admin
  #connector:
   # type: http
    #port: 3001

logging:
  level: INFO
  loggers:
    com.karenngomes: DEBUG
    org.hibernate: WARN
    io.dropwizard: INFO
    org.eclipse.jetty.servlets: INFO


database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver
  user: userdb
  password: passworddb
  url: jdbc:h2:./academicodb
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: update

